name: Pantavisor Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk_env: [stable, rc]
        include:
          - sdk_env: stable
            sdk_url: "https://pantavisor-ci.s3.amazonaws.com/meta-pantavisor/02-test/raspberrypi-armv8-scarthgap/panta-musl-x86_64-pantavisor-starter-cortexa53-raspberrypi-armv8-toolchain-021.sh"
          - sdk_env: rc
            sdk_url: "https://pantavisor-ci.s3.amazonaws.com/meta-pantavisor/024-rc2/raspberrypi-armv8-scarthgap/panta-musl-x86_64-pantavisor-starter-cortexa53-raspberrypi-armv8-toolchain-021.sh"

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl autoconf automake libtool cmake python3
      - name: Download SDK
        run: |
          curl -L -O ${{ matrix.sdk_url }}
          chmod +x *.sh
      - name: Install SDK
        run: |
          ./*.sh -y -d ~/sdk
      - name: Build
        run: |
          SETUP_FILE=$(find ~/sdk -name "environment-setup-cortexa53-raspberrypi-armv8-panta-linux-musl")
          source $SETUP_FILE
          ./configure --host=$HOST_SYS
          make -j$(nproc)
